development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: xourse_development
  pool: 5
  username: root
  password: pass

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: xourse_test
  pool: 5
  username: root
  password: pass

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: xourse_production
  pool: 5
  username: root
  password: pass